export const PRODUCT = [
  {
    name: "Pizaa",
    price: "50",
    id: "1",
    // quantity:"0",
    // img: require("https://yt3.googleusercontent.com/LEpz4Ig9TN-IEjD2cA6WTkyVQ_uHSC2WKtFZh8l2q7PBfrizeN35zGDu3LMC7oYdBRJOw7bW_w=s900-c-k-c0x00ffffff-no-rj"),
  },
  {
    name: "Pizza Ice-cream",
    price: "50",
    id: "2",
    // quantity:"0",
    // img: require("https://yt3.googleusercontent.com/LEpz4Ig9TN-IEjD2cA6WTkyVQ_uHSC2WKtFZh8l2q7PBfrizeN35zGDu3LMC7oYdBRJOw7bW_w=s900-c-k-c0x00ffffff-no-rj"),
  },
  {
    name: "Pizza Dog",
    price: "50",
    id: "3",
    // quantity:"0",
    // img: require("https://yt3.googleusercontent.com/LEpz4Ig9TN-IEjD2cA6WTkyVQ_uHSC2WKtFZh8l2q7PBfrizeN35zGDu3LMC7oYdBRJOw7bW_w=s900-c-k-c0x00ffffff-no-rj"),
  },
  {
    name: "Pizza Cat",
    price: "50",
    id: "4",
    // quantity:"0",
    // img: require("https://yt3.googleusercontent.com/LEpz4Ig9TN-IEjD2cA6WTkyVQ_uHSC2WKtFZh8l2q7PBfrizeN35zGDu3LMC7oYdBRJOw7bW_w=s900-c-k-c0x00ffffff-no-rj"),
  },
  {
    name: "Pizza Candy",
    price: "50",
    id: "5",
    // quantity:"0",
    // img: require("https://yt3.googleusercontent.com/LEpz4Ig9TN-IEjD2cA6WTkyVQ_uHSC2WKtFZh8l2q7PBfrizeN35zGDu3LMC7oYdBRJOw7bW_w=s900-c-k-c0x00ffffff-no-rj"),
  },
  {
    name: "Pizza Sugar",
    price: "50",
    id: "5",
    // quantity:"0",
    // img: require("https://yt3.googleusercontent.com/LEpz4Ig9TN-IEjD2cA6WTkyVQ_uHSC2WKtFZh8l2q7PBfrizeN35zGDu3LMC7oYdBRJOw7bW_w=s900-c-k-c0x00ffffff-no-rj"),
  },
  {
    name: "Pizza Seafood",
    price: "50",
    id: "5",
    // quantity:"0",
    // img: require("https://yt3.googleusercontent.com/LEpz4Ig9TN-IEjD2cA6WTkyVQ_uHSC2WKtFZh8l2q7PBfrizeN35zGDu3LMC7oYdBRJOw7bW_w=s900-c-k-c0x00ffffff-no-rj"),
  },
  {
    name: "Pizza Corn",
    price: "50",
    id: "5",
    // quantity:"0",
    // img: require("https://yt3.googleusercontent.com/LEpz4Ig9TN-IEjD2cA6WTkyVQ_uHSC2WKtFZh8l2q7PBfrizeN35zGDu3LMC7oYdBRJOw7bW_w=s900-c-k-c0x00ffffff-no-rj"),
  },
  {
    name: "Pizza Red",
    price: "50",
    id: "5",
    // quantity:"0",
    // img: require("https://yt3.googleusercontent.com/LEpz4Ig9TN-IEjD2cA6WTkyVQ_uHSC2WKtFZh8l2q7PBfrizeN35zGDu3LMC7oYdBRJOw7bW_w=s900-c-k-c0x00ffffff-no-rj"),
  },
  {
    name: "Pizza Yellow",
    price: "50",
    id: "5",
    // quantity:"0",
    // img: require("https://yt3.googleusercontent.com/LEpz4Ig9TN-IEjD2cA6WTkyVQ_uHSC2WKtFZh8l2q7PBfrizeN35zGDu3LMC7oYdBRJOw7bW_w=s900-c-k-c0x00ffffff-no-rj"),
  },
  {
    name: "Pizza Bird",
    price: "50",
    id: "5",
    // quantity:"0",
    // img: require("https://yt3.googleusercontent.com/LEpz4Ig9TN-IEjD2cA6WTkyVQ_uHSC2WKtFZh8l2q7PBfrizeN35zGDu3LMC7oYdBRJOw7bW_w=s900-c-k-c0x00ffffff-no-rj"),
  },

];